export const categories = [
	'All',
	'American drama',
	'Fiction',
	'Mass murder',
	'Illustrated books',
	'Criticism',
	'Biography & Autobiography',
	'Science fiction',
	'True Crime',
	'History',
	'Comics & Graphic Novels',
	'Multiple personality',
	'American poetry',
	'Computers',
	'Child development',
	'Actors',
	'Application software',
	'Drama',
	'Medical',
	'Cells',
	'Science',
	'Biology',
	'Art',
	'Mathematics'
];